### ISSUE TITLE
Stop editing the source.

### ISSUE THREAD

**Issue by RudyXIV** [Zilacon/APOC-End-Reset#1]
If you edit the source once more I will take action and press charges.

**Comment by Zilacon** [comment]
You programmed this for apoc as a open source plugin that i was going to release to the public as a GPL licensed plugin. You gave up on the plugin by not finishing it throwing a temper tantrum when i said it corrupted worlds and then quit the community.

This plugin project is not your "property" you programmed it under the guidance of me. With my instructions, my ideas, and also tested on my servers. My community's name is even on the plugin itself.

This repo also belongs to me, not you. It is a plugin for a open source api which anyone can edit or modify to how they see fit.

**Comment by Zilacon** [comment]
Also capsar did more work on this then you did.

**Comment by unarmed1618** [comment]
Yeah, Rudy, uh, what exactly are you getting at? Anything on Github not in a locked repo is effectively General Public License. You don't have any rights to it. Zilacon owns the Intellectual property, legally.

**Comment by thomas15v** [comment]
Hmmmm, I was trying to get it to work. But if this really is an issue. I want to remove it and place it on another repo. The only thing I reused of this was the way of regen the end and the MessageUtil.

**Comment by Capsar** [comment]
Uhmm editing is all fine with me. Just keep in mind we left Zilacon for a reason, Being a big selfish asshole only pointing out the bad things and using you for his own benefit. If you want to see for yourself or think otherwise, that's all fine with me.  Oh and yeah keep us in the credits / creators unless you start from scratch of course.

**Comment by Zilacon** [comment]
Being a selfish asshole? By asking the people who volunteered to be programmers for a network to make a working plugin?

Explain to me how this is selfish? You VOLUNTEERED! I did not force anyone to make anything, i asked.

And only pointing out the bad things? Its called your frist plugin test ever and i reported a very serious bug on it called world corruption and you all went ape shit and quit when i mentioned this. It was your first compiled jar and you guys acted like it was some grace of god and it was perfection.

And Rudy there went and started building swastikas all over my server and got banned by DarkMists soon after this. I have chat logs from me talking with you capsar where you said Rudy AKA FreakyFalse was acting immature and an asshole and that he was ignoring you. I can tell your best of friends agian but please do not make it sound like you 2 were in complete agreement when you were on my network because i will start pulling conversation logs and this will start to get very personal publicly.
